---

- name: Pull down fresh git code
  git:
    repo: "https://github.com/CommunityHoneyNetwork/{{ item }}.git"
    dest: "{{ chn_server_storage_path }}/{{ item }}"
    update: true
  with_items:
    - "mongodb"
    - "redis"
    - "hpfeeds"
    - "mnemosyne"
    - "chn-server"

- name: Build docker images
  docker_image:
    dockerfile: Dockerfile-ubuntu
    name: "stingar/{{ item }}:latest"
    path: "{{ chn_server_storage_path }}/{{ item }}"
  with_items:
    - "mongodb"
    - "redis"
    - "hpfeeds"
    - "mnemosyne"
    - "chn-server"

#- name: Pull in images
# docker_image:
#   name: "stingar/{{ item }}:{{ chn_version_tag }}"
# with_items:
#   - "mongodb"
#   - "redis"
#   - "hpfeeds"
#   - "mnemosyne"
#   - "chn-server"
