---

- name: Pull down fresh git code
  git:
    repo: "https://github.com/CommunityHoneyNetwork/{{ item }}.git"
    dest: "{{ chn_server_storage_path }}/{{ item }}"
    update: true
  with_items:
    - "chn-server"

- name: Build docker images
  docker_image:
    name: "stingar/{{ item }}:latest"
    path: "{{ chn_server_storage_path }}/{{ item }}"
  loop:
    - "chn-server"
